### ISSUE TITLE
git:clone is not a dokku command.

### ISSUE THREAD

**Issue by luizpicolo** [dokku/smoke-test-app#1]
When executing the command `dokku git:clone --build tests https://github.com/dokku/smoke-test-app.git`

The error below is returned

 ```bash
!     `git:clone --build tests https://github.com/dokku/smoke-test-app.git` is not a dokku command.
!     See `dokku help` for a list of available commands.
```

My version of Dokku is: **dokku version 0.22.8**

**Comment by josegonzalez** [comment]
This command isn't available yet, the repository is just here to support a pull request.
